version: '3.1'

services:
  app:
    container_name: postsapi-app
    image: node:lts-alpine
    ports:
      - 3333:3333
  
  db:
    container_name: postsapi-db
    image: postgres
    restart: always
    volumes:
      - postsapi_db:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    env_file:
      - .env

  adminer:
    container_name: postsapi-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postsapi_db: