POST http://localhost:3333/api/posts
Content-Type: application/json

{
    "title": "Post 2",
    "text": "Some text 2",
    "author": "Alex",
    "test": "hello"
}

###

GET http://localhost:3333/api/posts

###

GET http://localhost:3333/api/posts?skip=5&limit=5

###

GET http://localhost:3333/api/posts/125

###

PATCH http://localhost:3333/api/posts/120
Content-Type: application/json

{
    "title": "Post",
    "text": "Some text"
}

###

DELETE http://localhost:3333/api/posts/12

###

GET http://localhost:3333/api/users/125

###

POST http://localhost:3333/api/users
Content-Type: application/json

{
    "email": "test@test.ru",
    "name": "test",
    "password": "pass"
}

###

PATCH http://localhost:3333/api/users/666
Content-Type: application/json

{
    "email": "test123455@test.ru",
    "name": "Jo",
    "password": "12345"
}

###

POST http://localhost:3333/api/login
Content-Type: application/json

{
    "email": "test123455@test.ru",
    "password": "12345"
}

###

POST http://localhost:3333/api/signup
Content-Type: application/json

{
    "email": "test123455@test.ru",
    "password": "12345",
    "name": "Jo"
}

###

GET http://localhost:3333/api/users/6
